version: 0.2

# Placeholder for environment variables set in the CodePipeline template
# variables:
#   ImageName: simple-docker-service-0ae3a3d5c677
#   Region: ap-southeast-2
#   AWSAcountID: 918025131303

phases:
  pre_build:
    commands:
      # Log in to Amazon ECR (Elastic Container Registry) 
      # $AWS_ACCOUNT_ID and $AWS_REGION are automatically provided by CodeBuild
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      
  build:
    commands:
      # Build the Docker image using the Dockerfile located in the root directory (.).
      - echo Building the Docker image...
      - docker build -t $ImageName .
      
  post_build:
    commands:
      # Tag the image with the ECR repository URI
      - echo Tagging the Docker image...
      - docker tag $ImageName:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ImageName:latest
      # Push the image to ECR
      - echo Pushing the Docker image to ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ImageName:latest

# CRITICAL FIX: Defines the output artifact that CodePipeline hands off to Elastic Beanstalk (EB).
# This artifact points EB to the ECR image that was just pushed.
artifacts:
  files:
    # This file contains the name/tag of the pushed image, which EB uses for deployment.
    - imagedefinitions.json 
  discard-paths: yes